name: "Repo Checker"
on:
  push:
    paths:
      - '**.sh'
      - 'fb/frameiterator'
      - 'frames/**'
      - 'fb/**.ass'
      - 'config.conf'
  pull_request:
  workflow_dispatch:

jobs:
  check-repo:
    runs-on: ubuntu-latest
    if: ${{ github.triggering_actor == github.repository_owner }}
    steps:
      - uses: actions/checkout@v3
      - name: execute
        env:
          tok_fb: ${{ secrets.TOK_FB }}
          tok_gif: ${{ secrets.TOK_GIF }}
        run: bash checkermain.sh "${tok_fb}" "${tok_gif}" >> "${GITHUB_STEP_SUMMARY}"